version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: main.py
      FLASK_ENV: development

  test:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh", "-c", "python -m unittest discover -s Tests -p 'testmock.py'"]
