name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run Tests
      run: docker-compose run test

  clean:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Clean Up
      run: docker-compose down --rmi all --volumes --remove-orphans
