name: Docker image cll

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  
  test:
   steps:
    -name: Run tests
     run: docker-compose run test

      
  clean:
   steps:
    - name: Clean up
      run: docker-compose down --rmi all --volumes --remove-orphans
